import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Poppins } from "next/font/google"; // Import Poppins font
import "./globals.css";
import ResponsiveAppBar from "./components/navbar/page";
import Footer from "./components/footer/page";

// Loading the Poppins font
const poppins = Poppins({
  weight: ["500", "700"], // You can choose specific weights
  subsets: ["latin"],
  variable: "--font-poppins",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>{/* Include any other meta tags or links if necessary */}</head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${poppins.variable} antialiased`}
      >
        <ResponsiveAppBar />
        {/* <main>{children}</main> */}
        <Footer />
      </body>
    </html>
  );
}
